# Pony: assertion failure after unhandled exception in Flask
